/*
 * Parking Reservation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wac_api

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI interface {


    // ReservationsGet Get /api/reservations
    // List all reservations 
     ReservationsGet(c *gin.Context)

    // ReservationsIdDelete Delete /api/reservations/:id
    // Delete a reservation 
     ReservationsIdDelete(c *gin.Context)

    // ReservationsIdPut Put /api/reservations/:id
    // Update a reservation 
     ReservationsIdPut(c *gin.Context)

    // ReservationsPost Post /api/reservations
    // Create a reservation 
     ReservationsPost(c *gin.Context)

}