/*
 * Parking Reservation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wac_api

import (
	"time"
)

type ReservationInput struct {

	LicensePlate string `json:"licensePlate"`

	Category string `json:"category"`

	Datetime time.Time `json:"datetime"`

	SpotNumber int32 `json:"spotNumber"`
}
