/*
 * Parking Reservation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wac_api

import (
	"time"
)

type Reservation struct {

	Id string `json:"id,omitempty"`

	LicensePlate string `json:"licensePlate,omitempty"`

	Category string `json:"category,omitempty"`

	Datetime time.Time `json:"datetime,omitempty"`

	SpotNumber int32 `json:"spotNumber,omitempty"`
}
